# Site settings 
title: Donovan Vincent Jr 💻🧮
author: 
  name: Donovan Vincent Jr 
  email: dvincen9@jh.edu

# Build settings 
remote_theme: jekyll/minima

# Force this 
header_pages: 
  - about.md
  - research.md
  - lwm.md
